name: real_image

image_shape: &image_shape [3, 240, 320]
depth_shape: &depth_shape [1, 240, 320]
dataset_path: data/dataset_H480W640_process_fullobs_encoder.hdf5

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim, depth
  obs:
    camera_depth:
      shape: *depth_shape
      type: depth
    camera_rgb:
      shape: *image_shape
      type: rgb
    ee_pos:
      shape: [3]
      type: low_dim
    ee_quat:
      shape: [4]
      type: low_dim
    contact_force_z:
      shape: [3]
      type: lowdim
  action: 
    shape: [10]

env_runner:
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: False
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  seed: 42
  val_ratio: 0.02

