name: real_image

image_shape: &image_shape [3, 240, 320]
depth_shape: &depth_shape [1, 240, 320]
dataset_path: data/dataset_H480W640.hdf5

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim, depth
  obs:
    camera_depth:
      shape: *depth_shape
      type: depth
    camera_rgb:
      shape: *image_shape
      type: rgb
    ee_pose:
      shape: [3]
      type: low_dim
    ee_quat:
      shape: [4]
      type: low_dim
    contact_force_z:
      shape: [3]
      type: low_dim
  actions:
    shape: [10]
    persistent_dims: [7, 8]
    binary_dims: [9]

env_runner:
  _target_: diffusion_policy.env_runner.isaaclab_image_runner.IsaacLabImageRunner
  shape_meta: *shape_meta
  task_name: "Template-Threefingers-v0"
  n_test: 10
  n_test_vis: 3
  test_start_seed: 10000
  max_steps: 750
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  crf: 22
  past_action: ${past_action_visible}
  n_envs: 1
  image_shape: *image_shape
  depth_shape: *depth_shape
  enable_cameras: True
  headless: True
  device: "cuda:0"

dataset:
  _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  abs_action: False
  rotation_rep: 'rotation_6d'
  use_legacy_normalizer: False
  use_cache: True
  load_image_obs_from_hdf5: True
  repeat_single_frame_image_obs: True
  preload_single_frame_image_obs: True
  seed: 42
  val_ratio: 0.02
